// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: get_apache_info.proto

package agent_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetApacheInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetApacheInfoRequest) Reset() {
	*x = GetApacheInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_apache_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApacheInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApacheInfoRequest) ProtoMessage() {}

func (x *GetApacheInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_apache_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApacheInfoRequest.ProtoReflect.Descriptor instead.
func (*GetApacheInfoRequest) Descriptor() ([]byte, []int) {
	return file_get_apache_info_proto_rawDescGZIP(), []int{0}
}

type GetApacheInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List    []*SiteInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetApacheInfoResponse) Reset() {
	*x = GetApacheInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_apache_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApacheInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApacheInfoResponse) ProtoMessage() {}

func (x *GetApacheInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_apache_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApacheInfoResponse.ProtoReflect.Descriptor instead.
func (*GetApacheInfoResponse) Descriptor() ([]byte, []int) {
	return file_get_apache_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetApacheInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetApacheInfoResponse) GetList() []*SiteInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type SiteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listen       int32  `protobuf:"varint,1,opt,name=listen,proto3" json:"listen,omitempty"`
	DocumentRoot string `protobuf:"bytes,2,opt,name=documentRoot,proto3" json:"documentRoot,omitempty"`
	ServerAlias  string `protobuf:"bytes,3,opt,name=serverAlias,proto3" json:"serverAlias,omitempty"`
	ServerName   string `protobuf:"bytes,4,opt,name=serverName,proto3" json:"serverName,omitempty"`
	AccessTime   string `protobuf:"bytes,5,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	Logs         []*Log `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *SiteInfo) Reset() {
	*x = SiteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_apache_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteInfo) ProtoMessage() {}

func (x *SiteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_get_apache_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteInfo.ProtoReflect.Descriptor instead.
func (*SiteInfo) Descriptor() ([]byte, []int) {
	return file_get_apache_info_proto_rawDescGZIP(), []int{2}
}

func (x *SiteInfo) GetListen() int32 {
	if x != nil {
		return x.Listen
	}
	return 0
}

func (x *SiteInfo) GetDocumentRoot() string {
	if x != nil {
		return x.DocumentRoot
	}
	return ""
}

func (x *SiteInfo) GetServerAlias() string {
	if x != nil {
		return x.ServerAlias
	}
	return ""
}

func (x *SiteInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *SiteInfo) GetAccessTime() string {
	if x != nil {
		return x.AccessTime
	}
	return ""
}

func (x *SiteInfo) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Size         uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	AccessTime   string `protobuf:"bytes,3,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	ModifiedTime string `protobuf:"bytes,4,opt,name=modifiedTime,proto3" json:"modifiedTime,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_apache_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_get_apache_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_get_apache_info_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Log) GetAccessTime() string {
	if x != nil {
		return x.AccessTime
	}
	return ""
}

func (x *Log) GetModifiedTime() string {
	if x != nil {
		return x.ModifiedTime
	}
	return ""
}

var File_get_apache_info_proto protoreflect.FileDescriptor

var file_get_apache_info_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x70, 0x61, 0x63, 0x68,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x41, 0x70, 0x61, 0x63, 0x68, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x74, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xce, 0x01, 0x0a, 0x08, 0x53,
	0x69, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x6f, 0x6f, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x71, 0x0a, 0x03, 0x4c,
	0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x6f,
	0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x69,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x70, 0x61, 0x63, 0x68, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x58, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x70, 0x61, 0x63, 0x68, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x21, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x61, 0x63, 0x68, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x61, 0x63, 0x68, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_get_apache_info_proto_rawDescOnce sync.Once
	file_get_apache_info_proto_rawDescData = file_get_apache_info_proto_rawDesc
)

func file_get_apache_info_proto_rawDescGZIP() []byte {
	file_get_apache_info_proto_rawDescOnce.Do(func() {
		file_get_apache_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_apache_info_proto_rawDescData)
	})
	return file_get_apache_info_proto_rawDescData
}

var file_get_apache_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_get_apache_info_proto_goTypes = []any{
	(*GetApacheInfoRequest)(nil),  // 0: agent_proto.GetApacheInfoRequest
	(*GetApacheInfoResponse)(nil), // 1: agent_proto.GetApacheInfoResponse
	(*SiteInfo)(nil),              // 2: agent_proto.SiteInfo
	(*Log)(nil),                   // 3: agent_proto.Log
}
var file_get_apache_info_proto_depIdxs = []int32{
	2, // 0: agent_proto.GetApacheInfoResponse.list:type_name -> agent_proto.SiteInfo
	3, // 1: agent_proto.SiteInfo.logs:type_name -> agent_proto.Log
	0, // 2: agent_proto.GetApacheInfo.GetApacheInfo:input_type -> agent_proto.GetApacheInfoRequest
	1, // 3: agent_proto.GetApacheInfo.GetApacheInfo:output_type -> agent_proto.GetApacheInfoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_get_apache_info_proto_init() }
func file_get_apache_info_proto_init() {
	if File_get_apache_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_get_apache_info_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetApacheInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_apache_info_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetApacheInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_apache_info_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SiteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_apache_info_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_apache_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_apache_info_proto_goTypes,
		DependencyIndexes: file_get_apache_info_proto_depIdxs,
		MessageInfos:      file_get_apache_info_proto_msgTypes,
	}.Build()
	File_get_apache_info_proto = out.File
	file_get_apache_info_proto_rawDesc = nil
	file_get_apache_info_proto_goTypes = nil
	file_get_apache_info_proto_depIdxs = nil
}
