// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_sys_info.proto

package agent_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSysInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSysInfoRequest) Reset()         { *m = GetSysInfoRequest{} }
func (m *GetSysInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetSysInfoRequest) ProtoMessage()    {}
func (*GetSysInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81fdc3c41f7f3ba, []int{0}
}

func (m *GetSysInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSysInfoRequest.Unmarshal(m, b)
}
func (m *GetSysInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSysInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetSysInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSysInfoRequest.Merge(m, src)
}
func (m *GetSysInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetSysInfoRequest.Size(m)
}
func (m *GetSysInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSysInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSysInfoRequest proto.InternalMessageInfo

type GetSysInfoResponse struct {
	Message              string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Caption              string       `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	Timezone             string       `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	SysVersion           string       `protobuf:"bytes,4,opt,name=sysVersion,proto3" json:"sysVersion,omitempty"`
	SysType              string       `protobuf:"bytes,5,opt,name=sysType,proto3" json:"sysType,omitempty"`
	SysArch              string       `protobuf:"bytes,6,opt,name=sysArch,proto3" json:"sysArch,omitempty"`
	Hostname             string       `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Uptime               string       `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	BootTime             string       `protobuf:"bytes,9,opt,name=bootTime,proto3" json:"bootTime,omitempty"`
	Cpu                  string       `protobuf:"bytes,11,opt,name=cpu,proto3" json:"cpu,omitempty"`
	CpuProcessor         string       `protobuf:"bytes,12,opt,name=cpuProcessor,proto3" json:"cpuProcessor,omitempty"`
	LoadAverage          *LoadAverage `protobuf:"bytes,13,opt,name=loadAverage,proto3" json:"loadAverage,omitempty"`
	Memory               string       `protobuf:"bytes,14,opt,name=memory,proto3" json:"memory,omitempty"`
	Ips                  []string     `protobuf:"bytes,15,rep,name=ips,proto3" json:"ips,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetSysInfoResponse) Reset()         { *m = GetSysInfoResponse{} }
func (m *GetSysInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetSysInfoResponse) ProtoMessage()    {}
func (*GetSysInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81fdc3c41f7f3ba, []int{1}
}

func (m *GetSysInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSysInfoResponse.Unmarshal(m, b)
}
func (m *GetSysInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSysInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetSysInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSysInfoResponse.Merge(m, src)
}
func (m *GetSysInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetSysInfoResponse.Size(m)
}
func (m *GetSysInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSysInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSysInfoResponse proto.InternalMessageInfo

func (m *GetSysInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSysInfoResponse) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *GetSysInfoResponse) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *GetSysInfoResponse) GetSysVersion() string {
	if m != nil {
		return m.SysVersion
	}
	return ""
}

func (m *GetSysInfoResponse) GetSysType() string {
	if m != nil {
		return m.SysType
	}
	return ""
}

func (m *GetSysInfoResponse) GetSysArch() string {
	if m != nil {
		return m.SysArch
	}
	return ""
}

func (m *GetSysInfoResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GetSysInfoResponse) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *GetSysInfoResponse) GetBootTime() string {
	if m != nil {
		return m.BootTime
	}
	return ""
}

func (m *GetSysInfoResponse) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

func (m *GetSysInfoResponse) GetCpuProcessor() string {
	if m != nil {
		return m.CpuProcessor
	}
	return ""
}

func (m *GetSysInfoResponse) GetLoadAverage() *LoadAverage {
	if m != nil {
		return m.LoadAverage
	}
	return nil
}

func (m *GetSysInfoResponse) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *GetSysInfoResponse) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

type LoadAverage struct {
	One                  string   `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Five                 string   `protobuf:"bytes,2,opt,name=five,proto3" json:"five,omitempty"`
	Fifteen              string   `protobuf:"bytes,3,opt,name=fifteen,proto3" json:"fifteen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadAverage) Reset()         { *m = LoadAverage{} }
func (m *LoadAverage) String() string { return proto.CompactTextString(m) }
func (*LoadAverage) ProtoMessage()    {}
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81fdc3c41f7f3ba, []int{2}
}

func (m *LoadAverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadAverage.Unmarshal(m, b)
}
func (m *LoadAverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadAverage.Marshal(b, m, deterministic)
}
func (m *LoadAverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadAverage.Merge(m, src)
}
func (m *LoadAverage) XXX_Size() int {
	return xxx_messageInfo_LoadAverage.Size(m)
}
func (m *LoadAverage) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadAverage.DiscardUnknown(m)
}

var xxx_messageInfo_LoadAverage proto.InternalMessageInfo

func (m *LoadAverage) GetOne() string {
	if m != nil {
		return m.One
	}
	return ""
}

func (m *LoadAverage) GetFive() string {
	if m != nil {
		return m.Five
	}
	return ""
}

func (m *LoadAverage) GetFifteen() string {
	if m != nil {
		return m.Fifteen
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSysInfoRequest)(nil), "agent_proto.GetSysInfoRequest")
	proto.RegisterType((*GetSysInfoResponse)(nil), "agent_proto.GetSysInfoResponse")
	proto.RegisterType((*LoadAverage)(nil), "agent_proto.LoadAverage")
}

func init() {
	proto.RegisterFile("get_sys_info.proto", fileDescriptor_a81fdc3c41f7f3ba)
}

var fileDescriptor_a81fdc3c41f7f3ba = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x6a, 0xe3, 0x30,
	0x10, 0xc7, 0x37, 0xeb, 0x6c, 0x3e, 0xe4, 0x64, 0xb3, 0xab, 0x85, 0x45, 0xe4, 0x90, 0x0d, 0x3e,
	0xe5, 0xe4, 0x85, 0xf4, 0xd6, 0x5b, 0x7a, 0x29, 0x85, 0x96, 0x96, 0x34, 0xf4, 0x50, 0x28, 0xc1,
	0x71, 0xc7, 0x89, 0xa1, 0x96, 0x54, 0x8f, 0x1c, 0x70, 0x9f, 0xa7, 0x0f, 0x5a, 0x46, 0xb2, 0x13,
	0x87, 0xd2, 0x93, 0xe6, 0x37, 0xff, 0xf9, 0x62, 0x46, 0x8c, 0x6f, 0xc1, 0xac, 0xb1, 0xc4, 0x75,
	0x2a, 0x13, 0x15, 0xea, 0x5c, 0x19, 0xc5, 0xfd, 0x68, 0x0b, 0xd2, 0xac, 0x2d, 0x04, 0x7f, 0xd8,
	0xef, 0x4b, 0x30, 0xf7, 0x25, 0x5e, 0xc9, 0x44, 0x2d, 0xe1, 0xb5, 0x00, 0x34, 0xc1, 0xbb, 0xc7,
	0x78, 0xd3, 0x8b, 0x5a, 0x49, 0x04, 0x2e, 0x58, 0x37, 0x03, 0xc4, 0x68, 0x0b, 0xa2, 0x35, 0x6d,
	0xcd, 0xfa, 0xcb, 0x1a, 0x49, 0x89, 0x23, 0x6d, 0x52, 0x25, 0xc5, 0x77, 0xa7, 0x54, 0xc8, 0xc7,
	0xac, 0x67, 0xd2, 0x0c, 0xde, 0x94, 0x04, 0xe1, 0x59, 0xe9, 0xc0, 0x7c, 0xc2, 0x18, 0x96, 0xf8,
	0x00, 0x39, 0x52, 0x62, 0xdb, 0xaa, 0x0d, 0x0f, 0x55, 0xc5, 0x12, 0x57, 0xa5, 0x06, 0xf1, 0xc3,
	0x55, 0xad, 0xb0, 0x52, 0x16, 0x79, 0xbc, 0x13, 0x9d, 0x83, 0x42, 0x48, 0xfd, 0x76, 0x0a, 0x8d,
	0x8c, 0x32, 0x10, 0x5d, 0xd7, 0xaf, 0x66, 0xfe, 0x97, 0x75, 0x0a, 0x4d, 0xdd, 0x45, 0xcf, 0x2a,
	0x15, 0x51, 0xce, 0x46, 0x29, 0xb3, 0x22, 0xa5, 0xef, 0x72, 0x6a, 0xe6, 0xbf, 0x98, 0x17, 0xeb,
	0x42, 0xf8, 0xd6, 0x4d, 0x26, 0x0f, 0xd8, 0x20, 0xd6, 0xc5, 0x5d, 0xae, 0x62, 0x40, 0x54, 0xb9,
	0x18, 0x58, 0xe9, 0xc4, 0xc7, 0xcf, 0x99, 0xff, 0xa2, 0xa2, 0xe7, 0xc5, 0x1e, 0x72, 0xda, 0xd6,
	0x70, 0xda, 0x9a, 0xf9, 0x73, 0x11, 0x36, 0x16, 0x1f, 0x5e, 0x1f, 0xf5, 0x65, 0x33, 0x98, 0xa6,
	0xcc, 0x20, 0x53, 0x79, 0x29, 0x7e, 0xba, 0x29, 0x1d, 0xd1, 0x24, 0xa9, 0x46, 0x31, 0x9a, 0x7a,
	0x34, 0x49, 0xaa, 0x31, 0xb8, 0x61, 0x7e, 0xa3, 0x0a, 0x05, 0xd0, 0x96, 0xdd, 0x69, 0xc8, 0xe4,
	0x9c, 0xb5, 0x93, 0x74, 0x0f, 0xd5, 0x4d, 0xac, 0x4d, 0xab, 0x4b, 0xd2, 0xc4, 0x00, 0xc8, 0xea,
	0x1e, 0x35, 0xce, 0x9f, 0x18, 0x3b, 0x1e, 0x9d, 0xdf, 0x9e, 0xd0, 0xe4, 0x64, 0xf6, 0x4f, 0x3f,
	0x66, 0xfc, 0xef, 0x4b, 0xdd, 0xfd, 0x9d, 0xe0, 0xdb, 0xc5, 0xe8, 0x71, 0x18, 0xfe, 0x6f, 0x44,
	0x6d, 0x3a, 0xf6, 0x39, 0xfb, 0x08, 0x00, 0x00, 0xff, 0xff, 0x47, 0x5c, 0x6f, 0xc1, 0xa4, 0x02,
	0x00, 0x00,
}
