// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_apache_info.proto

package agent_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetApacheInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApacheInfoRequest) Reset()         { *m = GetApacheInfoRequest{} }
func (m *GetApacheInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetApacheInfoRequest) ProtoMessage()    {}
func (*GetApacheInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ab0e845f9590c50, []int{0}
}

func (m *GetApacheInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApacheInfoRequest.Unmarshal(m, b)
}
func (m *GetApacheInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApacheInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetApacheInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApacheInfoRequest.Merge(m, src)
}
func (m *GetApacheInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetApacheInfoRequest.Size(m)
}
func (m *GetApacheInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApacheInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApacheInfoRequest proto.InternalMessageInfo

type GetApacheInfoResponse struct {
	Message              string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List                 []*SiteInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetApacheInfoResponse) Reset()         { *m = GetApacheInfoResponse{} }
func (m *GetApacheInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetApacheInfoResponse) ProtoMessage()    {}
func (*GetApacheInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ab0e845f9590c50, []int{1}
}

func (m *GetApacheInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApacheInfoResponse.Unmarshal(m, b)
}
func (m *GetApacheInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApacheInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetApacheInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApacheInfoResponse.Merge(m, src)
}
func (m *GetApacheInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetApacheInfoResponse.Size(m)
}
func (m *GetApacheInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApacheInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApacheInfoResponse proto.InternalMessageInfo

func (m *GetApacheInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetApacheInfoResponse) GetList() []*SiteInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type SiteInfo struct {
	Listen               int32    `protobuf:"varint,1,opt,name=listen,proto3" json:"listen,omitempty"`
	DocumentRoot         string   `protobuf:"bytes,2,opt,name=documentRoot,proto3" json:"documentRoot,omitempty"`
	ServerAlias          string   `protobuf:"bytes,3,opt,name=serverAlias,proto3" json:"serverAlias,omitempty"`
	ServerName           string   `protobuf:"bytes,4,opt,name=serverName,proto3" json:"serverName,omitempty"`
	AccessTime           string   `protobuf:"bytes,5,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SiteInfo) Reset()         { *m = SiteInfo{} }
func (m *SiteInfo) String() string { return proto.CompactTextString(m) }
func (*SiteInfo) ProtoMessage()    {}
func (*SiteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ab0e845f9590c50, []int{2}
}

func (m *SiteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiteInfo.Unmarshal(m, b)
}
func (m *SiteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiteInfo.Marshal(b, m, deterministic)
}
func (m *SiteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiteInfo.Merge(m, src)
}
func (m *SiteInfo) XXX_Size() int {
	return xxx_messageInfo_SiteInfo.Size(m)
}
func (m *SiteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SiteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SiteInfo proto.InternalMessageInfo

func (m *SiteInfo) GetListen() int32 {
	if m != nil {
		return m.Listen
	}
	return 0
}

func (m *SiteInfo) GetDocumentRoot() string {
	if m != nil {
		return m.DocumentRoot
	}
	return ""
}

func (m *SiteInfo) GetServerAlias() string {
	if m != nil {
		return m.ServerAlias
	}
	return ""
}

func (m *SiteInfo) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *SiteInfo) GetAccessTime() string {
	if m != nil {
		return m.AccessTime
	}
	return ""
}

func (m *SiteInfo) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	AccessTime           string   `protobuf:"bytes,3,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	ModifiedTime         string   `protobuf:"bytes,4,opt,name=modifiedTime,proto3" json:"modifiedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ab0e845f9590c50, []int{3}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Log) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Log) GetAccessTime() string {
	if m != nil {
		return m.AccessTime
	}
	return ""
}

func (m *Log) GetModifiedTime() string {
	if m != nil {
		return m.ModifiedTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetApacheInfoRequest)(nil), "agent_proto.GetApacheInfoRequest")
	proto.RegisterType((*GetApacheInfoResponse)(nil), "agent_proto.GetApacheInfoResponse")
	proto.RegisterType((*SiteInfo)(nil), "agent_proto.SiteInfo")
	proto.RegisterType((*Log)(nil), "agent_proto.Log")
}

func init() {
	proto.RegisterFile("get_apache_info.proto", fileDescriptor_8ab0e845f9590c50)
}

var fileDescriptor_8ab0e845f9590c50 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xad, 0x49, 0xab, 0x4e, 0x5b, 0x94, 0xc5, 0x96, 0xc5, 0x83, 0xd4, 0xc5, 0x43, 0xbd,
	0x44, 0xa8, 0x4f, 0x50, 0x2f, 0x22, 0x14, 0x0f, 0xd1, 0x83, 0x88, 0x50, 0xd6, 0x74, 0x1a, 0x17,
	0x9a, 0xdd, 0xb4, 0xb3, 0x15, 0xf4, 0x21, 0x7d, 0x26, 0xc9, 0xc4, 0x62, 0x52, 0xc5, 0x53, 0xf6,
	0xff, 0xe6, 0x67, 0xfe, 0x99, 0x0c, 0xf4, 0x52, 0xf4, 0x53, 0x9d, 0xeb, 0xe4, 0x15, 0xa7, 0xc6,
	0xce, 0x5d, 0x94, 0xaf, 0x9c, 0x77, 0xa2, 0xad, 0x53, 0xb4, 0x7e, 0xca, 0x42, 0xf5, 0xe1, 0xf8,
	0x06, 0xfd, 0x98, 0x4d, 0xb7, 0x76, 0xee, 0x62, 0x5c, 0xae, 0x91, 0xbc, 0x7a, 0x86, 0xde, 0x16,
	0xa7, 0xdc, 0x59, 0x42, 0x21, 0x61, 0x2f, 0x43, 0x22, 0x9d, 0xa2, 0x6c, 0x0c, 0x1a, 0xc3, 0x83,
	0x78, 0x23, 0xc5, 0x05, 0x84, 0x0b, 0x43, 0x5e, 0xee, 0x0e, 0x82, 0x61, 0x7b, 0xd4, 0x8b, 0x2a,
	0x31, 0xd1, 0xbd, 0xf1, 0x65, 0x1b, 0xb6, 0xa8, 0xcf, 0x06, 0xec, 0x6f, 0x90, 0xe8, 0x43, 0xab,
	0x80, 0x68, 0xb9, 0x61, 0x33, 0xfe, 0x56, 0x42, 0x41, 0x67, 0xe6, 0x92, 0x75, 0x86, 0xd6, 0xc7,
	0xce, 0x15, 0x7d, 0x8b, 0xb8, 0x1a, 0x13, 0x03, 0x68, 0x13, 0xae, 0xde, 0x70, 0x35, 0x5e, 0x18,
	0x4d, 0x32, 0x60, 0x4b, 0x15, 0x89, 0x53, 0x80, 0x52, 0xde, 0xe9, 0x0c, 0x65, 0xc8, 0x86, 0x0a,
	0x29, 0xea, 0x3a, 0x49, 0x90, 0xe8, 0xc1, 0x64, 0x28, 0x9b, 0x65, 0xfd, 0x87, 0x88, 0x73, 0x08,
	0x17, 0x2e, 0x25, 0xd9, 0xe2, 0xad, 0x8e, 0x6a, 0x5b, 0x4d, 0x5c, 0x1a, 0x73, 0x55, 0x2d, 0x21,
	0x98, 0xb8, 0x54, 0x08, 0x08, 0xfd, 0x7b, 0xbe, 0xf9, 0x33, 0xfc, 0x2e, 0x18, 0x99, 0x0f, 0xe4,
	0xf1, 0xc3, 0x98, 0xdf, 0x5b, 0xa1, 0xc1, 0xaf, 0x50, 0x05, 0x9d, 0xcc, 0xcd, 0xcc, 0xdc, 0xe0,
	0x8c, 0x1d, 0xe5, 0xd8, 0x35, 0x36, 0x32, 0xd0, 0xad, 0x5d, 0x48, 0x3c, 0x6e, 0x83, 0xb3, 0xda,
	0xb0, 0x7f, 0x9d, 0xf9, 0x44, 0xfd, 0x67, 0x29, 0x2f, 0xae, 0x76, 0xae, 0x0f, 0x9f, 0xba, 0xd1,
	0x65, 0xc5, 0xf8, 0xd2, 0xe2, 0xcf, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0x64, 0x31,
	0x54, 0x62, 0x02, 0x00, 0x00,
}
