// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: get_sys_info.proto

package agent_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSysInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSysInfoRequest) Reset() {
	*x = GetSysInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_sys_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSysInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSysInfoRequest) ProtoMessage() {}

func (x *GetSysInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_sys_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSysInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSysInfoRequest) Descriptor() ([]byte, []int) {
	return file_get_sys_info_proto_rawDescGZIP(), []int{0}
}

type GetSysInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message      string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Caption      string       `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	Timezone     string       `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	SysVersion   string       `protobuf:"bytes,4,opt,name=sysVersion,proto3" json:"sysVersion,omitempty"`
	SysType      string       `protobuf:"bytes,5,opt,name=sysType,proto3" json:"sysType,omitempty"`
	SysArch      string       `protobuf:"bytes,6,opt,name=sysArch,proto3" json:"sysArch,omitempty"`
	Hostname     string       `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Uptime       string       `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	BootTime     string       `protobuf:"bytes,9,opt,name=bootTime,proto3" json:"bootTime,omitempty"`
	Cpu          string       `protobuf:"bytes,11,opt,name=cpu,proto3" json:"cpu,omitempty"`
	CpuProcessor string       `protobuf:"bytes,12,opt,name=cpuProcessor,proto3" json:"cpuProcessor,omitempty"`
	LoadAverage  *LoadAverage `protobuf:"bytes,13,opt,name=loadAverage,proto3" json:"loadAverage,omitempty"`
	Memory       string       `protobuf:"bytes,14,opt,name=memory,proto3" json:"memory,omitempty"`
	Ips          []string     `protobuf:"bytes,15,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *GetSysInfoResponse) Reset() {
	*x = GetSysInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_sys_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSysInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSysInfoResponse) ProtoMessage() {}

func (x *GetSysInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_sys_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSysInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSysInfoResponse) Descriptor() ([]byte, []int) {
	return file_get_sys_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetSysInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSysInfoResponse) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *GetSysInfoResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GetSysInfoResponse) GetSysVersion() string {
	if x != nil {
		return x.SysVersion
	}
	return ""
}

func (x *GetSysInfoResponse) GetSysType() string {
	if x != nil {
		return x.SysType
	}
	return ""
}

func (x *GetSysInfoResponse) GetSysArch() string {
	if x != nil {
		return x.SysArch
	}
	return ""
}

func (x *GetSysInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetSysInfoResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *GetSysInfoResponse) GetBootTime() string {
	if x != nil {
		return x.BootTime
	}
	return ""
}

func (x *GetSysInfoResponse) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *GetSysInfoResponse) GetCpuProcessor() string {
	if x != nil {
		return x.CpuProcessor
	}
	return ""
}

func (x *GetSysInfoResponse) GetLoadAverage() *LoadAverage {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

func (x *GetSysInfoResponse) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *GetSysInfoResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type LoadAverage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One     string `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Five    string `protobuf:"bytes,2,opt,name=five,proto3" json:"five,omitempty"`
	Fifteen string `protobuf:"bytes,3,opt,name=fifteen,proto3" json:"fifteen,omitempty"`
}

func (x *LoadAverage) Reset() {
	*x = LoadAverage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_sys_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAverage) ProtoMessage() {}

func (x *LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_get_sys_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAverage.ProtoReflect.Descriptor instead.
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return file_get_sys_info_proto_rawDescGZIP(), []int{2}
}

func (x *LoadAverage) GetOne() string {
	if x != nil {
		return x.One
	}
	return ""
}

func (x *LoadAverage) GetFive() string {
	if x != nil {
		return x.Five
	}
	return ""
}

func (x *LoadAverage) GetFifteen() string {
	if x != nil {
		return x.Fifteen
	}
	return ""
}

var File_get_sys_info_proto protoreflect.FileDescriptor

var file_get_sys_info_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x79, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa4, 0x03, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x79,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x79, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x79, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x79, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x41, 0x72,
	0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x73, 0x41, 0x72, 0x63,
	0x68, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x70, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x70, 0x75, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x70, 0x75, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x70, 0x75, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x3a, 0x0a, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x70, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x22, 0x4d, 0x0a,
	0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69,
	0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x32, 0x5d, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4f, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_get_sys_info_proto_rawDescOnce sync.Once
	file_get_sys_info_proto_rawDescData = file_get_sys_info_proto_rawDesc
)

func file_get_sys_info_proto_rawDescGZIP() []byte {
	file_get_sys_info_proto_rawDescOnce.Do(func() {
		file_get_sys_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_sys_info_proto_rawDescData)
	})
	return file_get_sys_info_proto_rawDescData
}

var file_get_sys_info_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_get_sys_info_proto_goTypes = []any{
	(*GetSysInfoRequest)(nil),  // 0: agent_proto.GetSysInfoRequest
	(*GetSysInfoResponse)(nil), // 1: agent_proto.GetSysInfoResponse
	(*LoadAverage)(nil),        // 2: agent_proto.LoadAverage
}
var file_get_sys_info_proto_depIdxs = []int32{
	2, // 0: agent_proto.GetSysInfoResponse.loadAverage:type_name -> agent_proto.LoadAverage
	0, // 1: agent_proto.GetSysInfo.GetSysInfo:input_type -> agent_proto.GetSysInfoRequest
	1, // 2: agent_proto.GetSysInfo.GetSysInfo:output_type -> agent_proto.GetSysInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_get_sys_info_proto_init() }
func file_get_sys_info_proto_init() {
	if File_get_sys_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_get_sys_info_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetSysInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_sys_info_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetSysInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_sys_info_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LoadAverage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_sys_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_sys_info_proto_goTypes,
		DependencyIndexes: file_get_sys_info_proto_depIdxs,
		MessageInfos:      file_get_sys_info_proto_msgTypes,
	}.Build()
	File_get_sys_info_proto = out.File
	file_get_sys_info_proto_rawDesc = nil
	file_get_sys_info_proto_goTypes = nil
	file_get_sys_info_proto_depIdxs = nil
}
