// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: response_code.proto

package agent_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCode int32

const (
	ResponseCode_OK                   ResponseCode = 0
	ResponseCode_PARAM_ERROR          ResponseCode = 400
	ResponseCode_UNSUPPORTED          ResponseCode = 401
	ResponseCode_SERVER_ERROR         ResponseCode = 500
	ResponseCode_SERVER_CONFIG_ERROR  ResponseCode = 501
	ResponseCode_UNKNOWN_SERVER_ERROR ResponseCode = 599
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0:   "OK",
		400: "PARAM_ERROR",
		401: "UNSUPPORTED",
		500: "SERVER_ERROR",
		501: "SERVER_CONFIG_ERROR",
		599: "UNKNOWN_SERVER_ERROR",
	}
	ResponseCode_value = map[string]int32{
		"OK":                   0,
		"PARAM_ERROR":          400,
		"UNSUPPORTED":          401,
		"SERVER_ERROR":         500,
		"SERVER_CONFIG_ERROR":  501,
		"UNKNOWN_SERVER_ERROR": 599,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_response_code_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_response_code_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_response_code_proto_rawDescGZIP(), []int{0}
}

var File_response_code_proto protoreflect.FileDescriptor

var file_response_code_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0x82, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0b, 0x50,
	0x41, 0x52, 0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x90, 0x03, 0x12, 0x10, 0x0a,
	0x0b, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x91, 0x03, 0x12,
	0x11, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0xf4, 0x03, 0x12, 0x18, 0x0a, 0x13, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e,
	0x46, 0x49, 0x47, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xf5, 0x03, 0x12, 0x19, 0x0a, 0x14,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0xd7, 0x04, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_response_code_proto_rawDescOnce sync.Once
	file_response_code_proto_rawDescData = file_response_code_proto_rawDesc
)

func file_response_code_proto_rawDescGZIP() []byte {
	file_response_code_proto_rawDescOnce.Do(func() {
		file_response_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_response_code_proto_rawDescData)
	})
	return file_response_code_proto_rawDescData
}

var file_response_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_response_code_proto_goTypes = []any{
	(ResponseCode)(0), // 0: agent_proto.ResponseCode
}
var file_response_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_code_proto_init() }
func file_response_code_proto_init() {
	if File_response_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_response_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_code_proto_goTypes,
		DependencyIndexes: file_response_code_proto_depIdxs,
		EnumInfos:         file_response_code_proto_enumTypes,
	}.Build()
	File_response_code_proto = out.File
	file_response_code_proto_rawDesc = nil
	file_response_code_proto_goTypes = nil
	file_response_code_proto_depIdxs = nil
}
